
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Pepper.Cli.Windows.Reader {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Reader : Terminal.Gui.Views.Window {
        
        private Terminal.Gui.Views.FrameView cardFrame;
        
        private Terminal.Gui.Views.Label cardTopLeftLabel;
        
        private Terminal.Gui.Views.Label cardTopRightLabel;
        
        private Terminal.Gui.Views.Window window;
        
        private Terminal.Gui.Views.Label cardBottomLeftLabel;
        
        private Terminal.Gui.Views.Label cardBottomRightLabel;
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.Label label2;
        
        private Terminal.Gui.Views.Label uidLabel;
        
        private Terminal.Gui.Views.Label label3;
        
        private Terminal.Gui.Views.Label tagTypeLabel;
        
        private Terminal.Gui.Views.Label label4;
        
        private Terminal.Gui.Views.Label tagSpecLabel;
        
        private Terminal.Gui.Views.Line line;
        
        private Terminal.Gui.Views.Label label5;
        
        private Terminal.Gui.Views.Label label6;
        
        private Terminal.Gui.Views.Label cardValueLabel;
        
        private Terminal.Gui.Views.Label label7;
        
        private Terminal.Gui.Views.Label suitLabel;
        
        private Terminal.Gui.Views.Label label8;
        
        private Terminal.Gui.Views.Label deckLabel;
        
        private Terminal.Gui.Views.ListView readHistoryList;
        
        private Terminal.Gui.Views.Label readHistoryLabel;
        
        private void InitializeComponent() {
            this.deckLabel = new Terminal.Gui.Views.Label();
            this.label8 = new Terminal.Gui.Views.Label();
            this.suitLabel = new Terminal.Gui.Views.Label();
            this.label7 = new Terminal.Gui.Views.Label();
            this.cardValueLabel = new Terminal.Gui.Views.Label();
            this.label6 = new Terminal.Gui.Views.Label();
            this.label5 = new Terminal.Gui.Views.Label();
            this.line = new Terminal.Gui.Views.Line();
            this.tagSpecLabel = new Terminal.Gui.Views.Label();
            this.label4 = new Terminal.Gui.Views.Label();
            this.tagTypeLabel = new Terminal.Gui.Views.Label();
            this.label3 = new Terminal.Gui.Views.Label();
            this.uidLabel = new Terminal.Gui.Views.Label();
            this.label2 = new Terminal.Gui.Views.Label();
            this.label = new Terminal.Gui.Views.Label();
            this.cardBottomRightLabel = new Terminal.Gui.Views.Label();
            this.cardBottomLeftLabel = new Terminal.Gui.Views.Label();
            this.window = new Terminal.Gui.Views.Window();
            this.cardTopRightLabel = new Terminal.Gui.Views.Label();
            this.cardTopLeftLabel = new Terminal.Gui.Views.Label();
            this.cardFrame = new Terminal.Gui.Views.FrameView();
            this.readHistoryList = new Terminal.Gui.Views.ListView();
            this.readHistoryLabel = new Terminal.Gui.Views.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "Card Reader";
            this.cardFrame.Width = 26;
            this.cardFrame.Height = 19;
            this.cardFrame.X = 3;
            this.cardFrame.Y = 4;
            this.cardFrame.Visible = true;
            this.cardFrame.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.cardFrame.CanFocus = true;
            this.cardFrame.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.Opaque;
            this.cardFrame.Data = "cardFrame";
            this.cardFrame.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.cardFrame.Title = "Card";
            this.Add(this.cardFrame);
            this.cardTopLeftLabel.Width = Dim.Auto();
            this.cardTopLeftLabel.Height = Dim.Auto();
            this.cardTopLeftLabel.X = 2;
            this.cardTopLeftLabel.Y = 1;
            this.cardTopLeftLabel.Visible = true;
            this.cardTopLeftLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.cardTopLeftLabel.CanFocus = false;
            this.cardTopLeftLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.cardTopLeftLabel.Data = "cardTopLeftLabel";
            this.cardTopLeftLabel.Text = "#";
            this.cardTopLeftLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.cardFrame.Add(this.cardTopLeftLabel);
            this.cardTopRightLabel.Width = Dim.Auto();
            this.cardTopRightLabel.Height = Dim.Auto();
            this.cardTopRightLabel.X = 20;
            this.cardTopRightLabel.Y = 1;
            this.cardTopRightLabel.Visible = true;
            this.cardTopRightLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.cardTopRightLabel.CanFocus = false;
            this.cardTopRightLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.cardTopRightLabel.Data = "cardTopRightLabel";
            this.cardTopRightLabel.Text = "#";
            this.cardTopRightLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.cardFrame.Add(this.cardTopRightLabel);
            this.window.Width = 15;
            this.window.Height = 12;
            this.window.X = 4;
            this.window.Y = 2;
            this.window.Visible = true;
            this.window.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.window.CanFocus = true;
            this.window.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.window.Modal = false;
            this.window.Data = "window";
            this.window.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.window.Title = "";
            this.cardFrame.Add(this.window);
            this.cardBottomLeftLabel.Width = Dim.Auto();
            this.cardBottomLeftLabel.Height = Dim.Auto();
            this.cardBottomLeftLabel.X = 2;
            this.cardBottomLeftLabel.Y = 13;
            this.cardBottomLeftLabel.Visible = true;
            this.cardBottomLeftLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.cardBottomLeftLabel.CanFocus = false;
            this.cardBottomLeftLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.cardBottomLeftLabel.Data = "cardBottomLeftLabel";
            this.cardBottomLeftLabel.Text = "#";
            this.cardBottomLeftLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.cardFrame.Add(this.cardBottomLeftLabel);
            this.cardBottomRightLabel.Width = Dim.Auto();
            this.cardBottomRightLabel.Height = Dim.Auto();
            this.cardBottomRightLabel.X = 20;
            this.cardBottomRightLabel.Y = 13;
            this.cardBottomRightLabel.Visible = true;
            this.cardBottomRightLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.cardBottomRightLabel.CanFocus = false;
            this.cardBottomRightLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.cardBottomRightLabel.Data = "cardBottomRightLabel";
            this.cardBottomRightLabel.Text = "#";
            this.cardBottomRightLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.cardFrame.Add(this.cardBottomRightLabel);
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 33;
            this.label.Y = 4;
            this.label.Visible = true;
            this.label.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label.CanFocus = false;
            this.label.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label.Data = "label";
            this.label.Text = "Tag Info";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.label2.Width = Dim.Auto();
            this.label2.Height = Dim.Auto();
            this.label2.X = 36;
            this.label2.Y = 6;
            this.label2.Visible = true;
            this.label2.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label2.CanFocus = false;
            this.label2.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label2.Data = "label2";
            this.label2.Text = "UID:";
            this.label2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label2);
            this.uidLabel.Width = Dim.Auto();
            this.uidLabel.Height = Dim.Auto();
            this.uidLabel.X = 48;
            this.uidLabel.Y = 6;
            this.uidLabel.Visible = true;
            this.uidLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.uidLabel.CanFocus = false;
            this.uidLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.uidLabel.Data = "uidLabel";
            this.uidLabel.Text = "Heya";
            this.uidLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.uidLabel);
            this.label3.Width = Dim.Auto();
            this.label3.Height = Dim.Auto();
            this.label3.X = 36;
            this.label3.Y = 8;
            this.label3.Visible = true;
            this.label3.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label3.CanFocus = false;
            this.label3.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label3.Data = "label3";
            this.label3.Text = "Tag Type:";
            this.label3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label3);
            this.tagTypeLabel.Width = Dim.Auto();
            this.tagTypeLabel.Height = Dim.Auto();
            this.tagTypeLabel.X = 48;
            this.tagTypeLabel.Y = 8;
            this.tagTypeLabel.Visible = true;
            this.tagTypeLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.tagTypeLabel.CanFocus = false;
            this.tagTypeLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.tagTypeLabel.Data = "tagTypeLabel";
            this.tagTypeLabel.Text = "Heya";
            this.tagTypeLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.tagTypeLabel);
            this.label4.Width = Dim.Auto();
            this.label4.Height = Dim.Auto();
            this.label4.X = 36;
            this.label4.Y = 10;
            this.label4.Visible = true;
            this.label4.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label4.CanFocus = false;
            this.label4.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label4.Data = "label4";
            this.label4.Text = "Spec:";
            this.label4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label4);
            this.tagSpecLabel.Width = Dim.Auto();
            this.tagSpecLabel.Height = Dim.Auto();
            this.tagSpecLabel.X = 48;
            this.tagSpecLabel.Y = 10;
            this.tagSpecLabel.Visible = true;
            this.tagSpecLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.tagSpecLabel.CanFocus = false;
            this.tagSpecLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.tagSpecLabel.Data = "tagSpecLabel";
            this.tagSpecLabel.Text = "Heya";
            this.tagSpecLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.tagSpecLabel);
            this.line.Width = 28;
            this.line.Height = 1;
            this.line.X = 33;
            this.line.Y = 12;
            this.line.Visible = true;
            this.line.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.line.CanFocus = false;
            this.line.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.line.Data = "line";
            this.line.Text = "";
            this.line.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.line);
            this.label5.Width = Dim.Auto();
            this.label5.Height = Dim.Auto();
            this.label5.X = 33;
            this.label5.Y = 14;
            this.label5.Visible = true;
            this.label5.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label5.CanFocus = false;
            this.label5.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label5.Data = "label5";
            this.label5.Text = "Card Info";
            this.label5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label5);
            this.label6.Width = Dim.Auto();
            this.label6.Height = Dim.Auto();
            this.label6.X = 36;
            this.label6.Y = 16;
            this.label6.Visible = true;
            this.label6.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label6.CanFocus = false;
            this.label6.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label6.Data = "label6";
            this.label6.Text = "Value:";
            this.label6.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label6);
            this.cardValueLabel.Width = Dim.Auto();
            this.cardValueLabel.Height = Dim.Auto();
            this.cardValueLabel.X = 48;
            this.cardValueLabel.Y = 16;
            this.cardValueLabel.Visible = true;
            this.cardValueLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.cardValueLabel.CanFocus = false;
            this.cardValueLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.cardValueLabel.Data = "cardValueLabel";
            this.cardValueLabel.Text = "Heya";
            this.cardValueLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.cardValueLabel);
            this.label7.Width = Dim.Auto();
            this.label7.Height = Dim.Auto();
            this.label7.X = 36;
            this.label7.Y = 18;
            this.label7.Visible = true;
            this.label7.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label7.CanFocus = false;
            this.label7.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label7.Data = "label7";
            this.label7.Text = "Suit:";
            this.label7.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label7);
            this.suitLabel.Width = Dim.Auto();
            this.suitLabel.Height = Dim.Auto();
            this.suitLabel.X = 48;
            this.suitLabel.Y = 18;
            this.suitLabel.Visible = true;
            this.suitLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.suitLabel.CanFocus = false;
            this.suitLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.suitLabel.Data = "suitLabel";
            this.suitLabel.Text = "Heya";
            this.suitLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.suitLabel);
            this.label8.Width = Dim.Auto();
            this.label8.Height = Dim.Auto();
            this.label8.X = 36;
            this.label8.Y = 20;
            this.label8.Visible = true;
            this.label8.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label8.CanFocus = false;
            this.label8.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.label8.Data = "label8";
            this.label8.Text = "Deck:";
            this.label8.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label8);
            this.deckLabel.Width = Dim.Auto();
            this.deckLabel.Height = Dim.Auto();
            this.deckLabel.X = 48;
            this.deckLabel.Y = 20;
            this.deckLabel.Visible = true;
            this.deckLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.deckLabel.CanFocus = false;
            this.deckLabel.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.deckLabel.Data = "deckLabel";
            this.deckLabel.Text = "Heya";
            this.deckLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.deckLabel);
            this.readHistoryLabel.Width = Dim.Auto();
            this.readHistoryLabel.Height = Dim.Auto();
            this.readHistoryLabel.X = 3;
            this.readHistoryLabel.Y = 25;
            this.readHistoryLabel.Visible = true;
            this.readHistoryLabel.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.readHistoryLabel.CanFocus = false;
            this.readHistoryLabel.Text = "Read Log:";
            this.Add(this.readHistoryLabel);
            this.readHistoryList.Width = Dim.Fill(0);
            this.readHistoryList.Height = Dim.Auto();
            this.readHistoryList.Visible = true;
            this.readHistoryList.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.readHistoryList.X = 3;
            this.readHistoryList.Y = 27;
            this.readHistoryList.CanFocus = true;
            this.Add(this.readHistoryList);
        }
    }
}
